plink:
  container: "genetics_latest.sif"
  gene_ref: "1000G_merged/glist-hg37.tsv"

genome_refs:
  merged_1kg: "1000G_merged/1000G_merged"
  deep_1kg: "deep_1kg/EUR/EUR_rsID"

mixer:
  container: "mixer.sif"
  ref_files: "mixer/"

tidyGWAS:
  container: "tidygwas_latest.sif"
  ref: "dbSNP155"

# Filepaths and container to run gctb
gctb:
  container: "genetics_latest.sif"
  ldm_s: "gctb/ukbEURu_imp_v3_HM3_n50k.chisq10.ldm.sparse"
  mbat_gene_list_b37: "gctb/glist_ensgid_hg19_v40.txt"
gcta:
  container: "genetics_latest.sif"

# using basic 7 million LD-matrix
sbayesrc:
  container: "sbayesrc_latest.sif"
  ldm: "gctb/ukbEUR_Imputed"
  annot: "gctb/annot_baseline2.2.txt"
